vapor/template

- Public/styles/app.css
- Resources/Views/base.leaf
- Resources/Views/hello.leaf
- Resources/Views/welcome.leaf
It's important to specify an explicit character encoding on every webpage in order for it to render properly.
According to the [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta):
> The `<meta>` element declaring the encoding must be inside the `<head>` element and within the first 1024 bytes of the HTML as some browsers only look at those bytes before choosing an encoding.
This PR adds the necessary tag to the base template.
> Add <meta charset="utf-8"> to base template

- .dockerignore
- manifest.yml
Before the Docker starts to build the image it copies all files into its context. By adding `.build` and `.swiftpm` to `.dockerignore` this process will be a lot faster resulting in faster Docker image builds if those folders exist.
> Make docker build faster by ignoring .build folder

- docker-compose.yml
In a dev environment it is _likely_ preferable not to require the user to bind mount their own SSL cert into the mysql service. One of the big differences between the `mysql/mysql-server` and `mysql` docker images is that the latter has the ability to generate a self-signed cert when it starts up.
Of course, for Vapor to communicate with it, the mysql config still needs to be modified to not use a certificate signing authority.
> Adjust for local dev env

- docker-compose.yml
The replica count is important for swarm deploys because as-is a swarm deploy will result in running both migrate and revert (doing both in an undefined order no less). With replicas specified as 0, you must choose to scale those services up in swarm environment.
> don't give migrate/revert any replicas in swarms

- Dockerfile
- cloud.yml
This PR:
* Updates the Dockerfile to use Swift 5.2 as it's now required by Vapor 4
* Fixes an unescaped line break in the Dockerfile which would cause `docker build` to fail
* Removes `cloud.yml` as Vapor Cloud is no longer a thing after February 29th
> Fixes and Vapor Cloud tidy

- Dockerfile
This way the Dockerfile doesn't have to keep getting updated for each point release. It can be put back to a hardcoded version on a case-by-case basis if a release breaks things.
> Pull from vapor/swift:latest, which now exists

- Dockerfile
Adding the `--system` and `--skel /dev/null` options to `useradd` prevents it from copying in extra skeleton files like Bash profiles that we don't want. We also explicitly specify the `vapor` GID along with the `vapor` UID in the `USER` command.
> Improve useradd invocation and other cleanup

- Dockerfile
Fixes an issue where uncommenting the line to copy over files in `Public` would fail as we've changed the working directory and `Public` is still in the original place
> Fix copy from location for Public directory

- Dockerfile
There's no value to a writable `Public` directory or contents thereof, since changes will not persist. Thus we write-protect the files by default to increase the difficulty of leveraging any potential compromise in the Vapor service, especially the difficulty of defacing any hosted content.
> Don't leave the Public directory or its contents writable by default

- Tests/AppTests/AppTests.swift
Building this file with Swift 5.3 generates the following warning:
`Backward matching of the unlabeled trailing closure is deprecated; label the argument with 'afterResponse' to suppress this warning`
This update suppresses the warning by passing the closure as an `afterResponse:` argument in `app.test`
> Update AppTests.swift for Swift 5.3

- docker-compose.yml
The `deploy: replicas: 0` configuration for the `migrate` and `revert` "services" in `docker-compose.yml` prevents `docker-compose up` from working correctly with them as of at least the current version of Docker Compose, possibly longer. It is more correct in either event to use `docker-compose run` for these instead.
> `docker-compose up migrate` should be `docker-compose run migrate`

- Sources/App/configure.swift
It's pretty common to need to change the port on the database.  Would be nice if the template handled that by default.
> Add port to default database setup.

- docker-compose.yml
Fixes #29 by using `name_kebab` instead of `name` as requested in https://github.com/vapor/toolbox/pull/323 .
Dependent upon https://github.com/vapor/toolbox/pull/353
> Use name_kebab in docker-compose

- Dockerfile
There's a type in Dockerfile from the template
> typo in `resources`

- Dockerfile
The base Ubuntu Docker images do not come with the root CA store installed, breaking anything using TLS. Install them in the runner image explicitly.
> Fix for missing root certificate store in base Ubuntu image

- manifest.yml
This fix consists of adding the folder to the manifest.yml file.
This should fix the problem of generating a new vapor project with the template and having no public folder generated.
closes #60
> Fix bug where public directory is not added when using the template

- .gitignore
Adding .env to .gitignore to prevent accidental pushing of .env file to a public repo.
> Adding .env to .gitignore

- Dockerfile
This change enables dependencies that rely on resource bundles (for example PhoneNumberKit), and the usage of `Bundle.module` inside the application.
> Copy SPM resource bundles to Docker image

- Dockerfile
Without the tzdata package installed, any Foundation call that involves Date formatting (most notably, ISO8601DateFormatter that is heavily relied upon by Vapor) will crash the application process with a SIGABRT.
> Install tzdata in the final Docker image

- Dockerfile
- Package.swift
- README.md
At the moment if you create a `vapor new` project it wont build for ARM without bumping the Dockerfile to `5.6` so I've gone ahead and bumped the defaults so hopefully this'll mitigate any confusion from end users.
> Bump default Swift Docker image version to 5.6. Bump Swift tools version to 5.6

- Sources/App/Controllers/TodoController.swift
I feel like `204 (No Content)` is the best default for the `TodoController`'s `DELETE` response, given that the controller is also returning an empty response body by default.
AFAIK, there aren’t any _strict_ rules as to whether it should be `200` or `204`, but comparing the [documentation for each](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE#responses)  would suggest that `204` is more salient choice.
> Return `204 (No Content)` instead of `200 (OK)` in `TodoController.delete`

- Dockerfile
Most apps can run without `libcurl4` and `libxml2`, and omitting them makes the run image significantly smaller. When they are needed, this PR makes installing them easier. It also helps draw attention to the fact that they have been omitted.
> Add commented Swift deps to Dockerfile to ease opt-in (resolves #86)

- Dockerfile
Glibc version difference between focal and jammy images results in a defunct run image
> Aligned base image used for the Run image

- .github/workflows/auto-template-creation.yml
- .github/workflows/test-template.yml
- CONTRIBUTING.md
- Dockerfile
- LICENSE
- Package.swift
- README.md
- Sources/App/configure.swift
- Sources/App/entrypoint.swift
- Sources/Run/main.swift
- Tests/AppTests/AppTests.swift
- docker-compose.yml
- manifest.yml
Makes the following updates:
- Make Swift 5.8 the default for generated projects
- Remove the separate `Run` target, making `App` the executable.
- Switch to using an `@main` entrypoint.
- Fix vapor/vapor#2648 (shoutout to @vzsg, who did most of the work on this)
- Update `README.md`, `CONTRIBUTING.md`, and `LICENSE`
- Require some more current minimum dependency versions in template `Package.swift`
- Update PostgreSQL version in template `docker-compose.yml`
- Major CI cleanups
Subsumes #78.
> Modernize for Swift 5.8

- Sources/App/configure.swift
Due to an issue with how the old APIs in PostgresKit and FluentPostgresDriver were deprecated, we must specify `SQLPostgresConfiguration` explicitly when creating the PostgreSQL database configuration to avoid a 60,000% penalty (yes, really - from 0.1s to 60s) when compiling `configure.swift`
> Work around a massive compile time regression in FluentPostgresDriver

- Sources/App/entrypoint.swift
This ensures the full error details, which are not always reported by the "error raised at top level" handler in the runtime, are logged.
> Report errors from `configure(_:)` through the app's logger before throwing

- Dockerfile
When no `Package.resolved` was present, the `Dockerfile` would generate an invalid command. This is now fixed.
Fixes #110.
> Fix Dockerfile when no Package.resolved is present

- manifest.yml
I was setting up Vapor for the first in a few years and didn't know what functions Fluent and Leaf were. For beginners, the setup wizard cannot be completed without trips to Google to learn more. This PR inlines what the tools are used for.
Before:
```bash
Would you like to use Fluent? (--fluent/--no-fluent)
y/n> n
fluent: No
Would you like to use Leaf? (--leaf/--no-leaf)
y/n> n
leaf: No
```
After:
```bash
Would you like to use Fluent (ORM)? (--fluent/--no-fluent)
y/n> n
fluent: No
Would you like to use Leaf (templating)? (--leaf/--no-leaf)
y/n> n
leaf: No
```
> Explain what Fluent and Leaf are during setup

- .github/dependabot.yml
- Dockerfile
- Package.swift
- Sources/App/entrypoint.swift
Uses the new async entrypoints in Vapor, updates the backtracing logic for Swift 5.9.1, and switches to using libjemalloc by default in built images.
Supersedes #116
> Async entrypoints and jemalloc

- Dockerfile
The template currently specifies `ubuntu:latest`, which can end up choosing a version of Ubuntu not officially supported by Swift. While this probably isn't critical given the use of statically linked executables, for full correctness we should pin to the newest supported version (Jammy at the time of this writing) instead.
> Pin runner image version

- Dockerfile
The error from Penny:
<kbd>
</kbd>   
This PR fixes that by providing the explicit path of the backtrace binary to Swift's runtime.
> Fix Dockerfile `unable to locate swift-backtrace`

- Sources/App/routes.swift
Currently when creating a new project without leaf, leading spaces are missing in `./Sources/App/routes.swift`
```swift
func routes(_ app: Application) throws {
app.get { req async in
```
This PR adds the missing leading spaces to match expectation
```swift
func routes(_ app: Application) throws {
app.get { req async in
```
Alternative considered modification was to move the mustache selection earlier, but caused `Error: Mustache error: bad unescape tag`, and was not able to find solution to resolve the issue.
```
func routes(_ app: Application) throws {{{#leaf}}
app.get { req async throws in
try await req.view.render("index", ["title": "Hello Vapor!"])
}{{/leaf}}{{^leaf}}
app.get { req async in
```
> Add leading spaces to routes.swift

- .github/workflows/test-template.yml
- Dockerfile
- Package.swift
- README.md
- Sources/App/Controllers/TodoController.swift
- docker-compose.yml
- manifest.yml
Updates the template for Swift 5.10
- Enables [strict concurrency checking](https://www.swift.org/documentation/concurrency/).
- Eliminates strict concurrency warnings.
- Removes the workaround for https://github.com/apple/swift-package-manager/issues/6940.  Confirmed this issue was fixed in swift 5.9.2.
This is an extension of work by @gwynne in #125.
> Update for Swift 5.10 and strict concurrency

- Sources/App/Models/Todo.swift
As per vapor/vapor#3180 and vapor/fluent-kit#601, the recent update to Fluent to add (nearly but not totally complete) `Sendable`-correctness results in a new warning of the form `Stored property '_id' of 'Sendable'-conforming class 'Todo' is mutable` for all types conforming to `Fields`, `Schema`, and/or `Model`. This adds the appropriate annotation to the template's `Todo` model for sample purposes.
(@gwynne  wrote this)
> Add @unchecked Sendable to Todo

- .github/workflows/test-template.yml
- Sources/App/Controllers/TodoController.swift
- Sources/App/DTOs/TodoDTO.swift
- Sources/App/Models/Todo.swift
- Tests/AppTests/AppTests.swift
- manifest.yml
The current recommendation when working with Fluent models is to use DTOs (data transfer objects) when decoding requests and encoding responses, rather than conforming the models themselves to `Content` as has been done historically. Our template project should reflect that recommendation.
Also includes tests for the `TodoController` routes when Fluent is selected.
> Use a data transfer object instead of direct model encoding/decoding

- Package.swift
- Sources/App/entrypoint.swift
- Tests/AppTests/AppTests.swift
Updates the template for the new async Application stuff and install NIO as a custom executor
Reliant on https://github.com/vapor/vapor/pull/3190 first
> Async Entry and Concurrency Executor Takeover

- Dockerfile
- Sources/App/Controllers/TodoController.swift
Pretty much what the title says.
> `Sendable` methods work in 5.10 and `swift package resolve --skip-update` is deprecated

- .github/workflows/auto-template-creation.yml
The template generation workflow [failed](https://github.com/vapor/template/actions/runs/9484457729) after the last version bump, as the toolbox was built and cached on Ubuntu 24.04, while the generation WF was set to run on 22.04 - and glibc is not backwards compatible like that.
> Run auto-template-creation workflow on 24.04

- Sources/App/entrypoint.swift
Has caused a few issues so disable by default.
Also clarity the comments
> Disable NIO as the Concurrency Global Executor by default

- .github/workflows/test-template.yml
- Dockerfile
Swift 6 has had [significant build time regressions](https://github.com/swiftlang/swift/issues/76555) which hopefully will become less significant by Swift 6.0.3.
Regardless, even on Swift 5.10, Swift noble seems to have build time / memory-usage regressions.
We've also had reports of similar OOM problems by Heorku users on Discord.
Swift build times are already not good, and there is a chance of running out of memory which will be confusing to users.
Let's not risk it and just use Swift jammy for now.
> Use Ubuntu `jammy` instead of `noble` for now

- Tests/AppTests/AppTests.swift
If a test throws an error the database won't be reverted and on successive tests or runs the DB will not be clean.
We can avoid this by running `app.autoRevert()` before each migration (This is also done in the Kodeco book).
P.S. By doing this we may not need the revert after the test is run
> Revert DB on the error path in tests

- .github/workflows/test-template.yml
- Dockerfile
Was just testing stuff in Penny, and Swift 6.0.3 seems to have fixed most of the discrepancies / regressions.
> Use Ubuntu/Swift Noble Again

- Sources/App/entrypoint.swift
Previously, if `app.execute()` threw an error, we would fail to shut down the `Application`.
> Ensure the app is shut down if app.execute() throws

- .gitignore
> fix: exclude .env.example from gitignore
