Package.swift
README.md

It's now required by Fluent and soon Vapor

Update to Swift 5.2 and macOS 10.15 

---

Sources/App/Migrations/CreateTodo.swift
Sources/App/Models/Todo.swift

- docs states that we should use UUID for ids
- docs references a convenience id() method for adding @ID properties using Fluent's recommended defaults

Updated Todo id field to match latest docs recommandations

---

Dockerfile

- Move SQLite install up above COPY layer so that it can be cached.
- Separate dependency resolution so that it can be cached.
Before this change, Docker image builds of a totally fresh project took approx. 4.5 minutes. After this change, any build not depending on changes to the `Package.resolved` file takes approx. 3.5 minutes.
You can see this at work with the snippets from two subsequent builds below. Note the layer that outputs the following on the second build:
```shell
Step 4/12 : RUN swift package resolve
---> Using cache
```
```shell
local:~/staging/toolbox/test_tmp_app (master)$ time docker build -t test:latest .
Sending build context to Docker daemon    107kB
Step 1/12 : FROM vapor/swift:5.2 as build
---> 040f13134f91
Step 2/12 : WORKDIR /build
---> Running in 48427648b0ec …
```

Create a docker layer that caches dependency resolution.

---

Dockerfile
docker-compose.yml

Remove any reference to `db` image when using SQLite (fixes #31, #34).

SQLite docker-compose fixes

---

Dockerfile

- Switch to using Ubuntu Focal as the base for the builder and runner images. Focal has much newer versions of most system packages and is considered stable for use with Swift 5.2. Significant performance improvements at runtime have been measured in locking behaviors in particular; for Vapor this means more requests served per second.
- We now always update all outdated packages installed on the builder and runner images. This means security updates are applied by default, helping to minimize potential security in libraries and executables during the build and in the final running container.
- The `Dockerfile` now switches to the `/build` working directory slightly later on, which improves Docker caching slightly.
- Rather than copying the entire `.build/release` directory from the …

Upgrade Dockerfile behaviors further

---

Dockerfile

Bump default Swift images to 5.3

---

Dockerfile
Package.swift
README.md
Resources/Views/index.leaf
Sources/App/configure.swift
Sources/App/routes.swift
manifest.yml

Requires Leaf being tagged as a release and possibly some toolbox work

Add Leaf Support

---

Package.swift

This content was moved in the recent efforts to expand and restructure the guides.

Update link to Swift server building guide

---

docker-compose.yml

Updating docker-compose to include mongo as a db service. 
added MONGO_URL to environment variable in app service.

Updated docker-compose file for mongo

---

Package.swift
Sources/App/Controllers/TodoController.swift
Sources/App/Migrations/CreateTodo.swift

Implemented async/await for Vapor template.

refactor to async/await

---

Dockerfile

Changes to the dockerfile. 
Added ubuntu:focal as the running image.
Added `--static-swift-stdlib` to the swift build command
Closes #58

Added swift static linking to swift build command and changed running image to ubuntu:focal in the dockerfile

---

.github/workflows/test-template.yml

Add CI To test the templates on a pull request. 
- Install the toolbox
- Run `vapor new`
- Test the template
- Build the docker container
closes #67

Add CI Test workflow

---

.github/workflows/test-template.yml

Add solution defined on https://github.com/actions/checkout/issues/766 for unsafe repository error

Update the test template

---

.github/workflows/auto-template-creation.yml

Add the same fix as the test workflow

Update auto-create workflow

---

Dockerfile

Install SQLite on runner as it's needed when static linking

---

Sources/App/routes.swift

Update last non-"async/await" routes to preferred "async/await" style

---

Dockerfile

Update Dockerfile for Swift 5.7 and improved SQLiteNIO

---

.github/workflows/test-template.yml

See https://securitylab.github.com/research/github-actions-untrusted-input/

Fix issue with CI's usage of Git Refs

---

Sources/App/configure.swift
manifest.yml

update Postgres database configuration function to use the latest version rather than the deprecated one.

fix deprecation notice for Postgres database configuration

---

.github/workflows/auto-template-creation.yml
Sources/App/configure.swift

Fixes vapor/fluent-mysql-driver#219.

Help out the typechecker to reduce build times

---

.github/dependabot.yml
.github/workflows/auto-template-creation.yml

CI updates

---

.github/workflows/test-template.yml
Dockerfile

Use Ubuntu 24.04 Noble Numbat in the template `Dockerfile` and the template's CI.

Update to Ubuntu 24.04 Noble Numbat

---

.github/workflows/test-template.yml
Dockerfile
Package.swift
Sources/App/configure.swift
Tests/AppTests/AppTests.swift

Updates the template to use Swift 6 and migrates the tests to Swift Testing, including an example of the `withApp { ... }` syntax

Swift Testing and Swift 6

---

docker-compose.yml

Remove obsolete version attribute from docker-compose.yml

---

Package.swift
Sources/App/Controllers/TodoController.swift
Sources/App/Migrations/CreateTodo.swift

Update template for Swift 6

---

.gitignore
.vscode/extensions.json
manifest.yml

Add recommended VS Code extensions

---

Sources/App/configure.swift
Sources/App/routes.swift
Tests/AppTests/AppTests.swift

The new Toolbox rewrite uses `swift-mustache`, which handles whitespace slightly differently than `vapor-community/mustache`

Update template for new Toolbox

---

README.md
TEMPLATE_README.md
manifest.yml

Add project README

---

Dockerfile
Package.swift
Tests/AppTests/AppTests.swift
manifest.yml

Use project name as executable target name

---

Package.swift
Tests/AppTests/AppTests.swift

No need to write the `withApp` function from scratch

Use VaporTesting's `withApp`
